"""Recovery-playbook emitter for the run_log learning loop (P0c).

Clusters past ``Recovery`` incidents (parsed from ``run_log.md`` RECOVERIES) into a
``recover``-skill-compatible markdown table: a curated *symptom → root cause →
action* taxonomy annotated with an empirical ``k/n`` success rate. Read-only — the
emitted markdown is reviewed/committed to ``guides/RECOVERY_PLAYBOOK.md`` separately.

See ``docs/specs/B4_runlog_miner_spec.md`` §2.2.
"""
from __future__ import annotations

from datetime import date

from .suggest import _succeeded  # shared "converged / pass" outcome test


def _text(rec) -> str:
    return f"{rec.trigger} {rec.diagnosis} {rec.fix}".lower()


# Ordered signature rules — first match wins. Each surfaces a recover-compatible
# (pattern, root_cause, action) triple; ``match`` inspects the combined recovery text.
SIGNATURES = [
    {
        "name": "density-trap",
        "pattern": "equilibration density drift / over-densified cell",
        "root_cause": "density_initial too close to RT density → over-densified trap",
        "action": "lower density_initial (~0.05 g/cm³); add an annealing cycle",
        "match": lambda t: ("density_initial" in t) or ("density" in t and ("densif" in t or "drift" in t)),
    },
    {
        "name": "sweep-below-Tg",
        "pattern": "extract_tg: too few temperature bins / glassy slope missing",
        "root_cause": "Tg sweep ceiling below MD Tg",
        "action": "raise tg_t_high_K / T_START toward ~2× expected Tg",
        "match": lambda t: ("below md tg" in t) or ("glassy slope" in t)
        or ("bins" in t and "tg" in t) or ("t_start" in t),
    },
    {
        "name": "lost-atoms",
        "pattern": "LAMMPS: lost atoms",
        "root_cause": "timestep too large or bad initial geometry",
        "action": "reduce dt_fs (e.g. → 0.5 fs); re-minimize",
        "match": lambda t: "lost atoms" in t,
    },
    {
        "name": "gpu-oom",
        "pattern": "GPU out of memory",
        "root_cause": "cell too large for available VRAM",
        "action": "halve mpi_ranks / reduce system size",
        "match": lambda t: ("out of memory" in t) or ("oom" in t) or ("vram" in t),
    },
]


def match_signature(rec):
    t = _text(rec)
    for sig in SIGNATURES:
        if sig["match"](t):
            return sig
    return None


def cluster_recoveries(records):
    """Return (clusters, unclustered).

    clusters: list of {name, pattern, root_cause, action, n, k, classes, runs}
    unclustered: list of {run, stage, diagnosis, fix, outcome}
    """
    buckets: dict = {}
    unclustered: list = []
    for r in records:
        for rec in r.recoveries:
            sig = match_signature(rec)
            if sig is None:
                unclustered.append({
                    "run": r.run_name, "stage": rec.stage,
                    "diagnosis": rec.diagnosis or rec.trigger,
                    "fix": rec.fix, "outcome": rec.outcome,
                })
                continue
            c = buckets.setdefault(sig["name"], {
                "name": sig["name"], "pattern": sig["pattern"],
                "root_cause": sig["root_cause"], "action": sig["action"],
                "n": 0, "k": 0, "classes": set(), "runs": set(),
            })
            c["n"] += 1
            if _succeeded(rec.outcome):
                c["k"] += 1
            if r.polymer_class:
                c["classes"].add(r.polymer_class)
            c["runs"].add(r.run_name)
    clusters = []
    for c in buckets.values():
        c["classes"] = sorted(c["classes"])
        c["runs"] = sorted(c["runs"])
        clusters.append(c)
    return clusters, unclustered


def build_playbook(records) -> str:
    clusters, unclustered = cluster_recoveries(records)
    n_runs = len(records)
    n_incidents = sum(len(r.recoveries) for r in records)
    lines = [
        "<!-- generated by `python -m tools.runlog_miner --playbook` — do not edit by hand;",
        "     regenerate: python -m tools.runlog_miner --playbook -o guides/RECOVERY_PLAYBOOK.md -->",
        "# Recovery Playbook",
        "",
        f"`runlog_miner` · {n_runs} runs · {n_incidents} recovery incidents · {date.today().isoformat()}",
        "",
        "Cluster-derived fixes distilled from past `run_log.md` RECOVERIES. The `recover`",
        "skill consults these first (ranked by empirical success rate) before its built-in taxonomy.",
        "",
    ]
    if not n_incidents:
        lines += [
            "_No recovery incidents in the corpus yet._ This file regenerates as runs accumulate.",
            "",
        ]
        return "\n".join(lines) + "\n"

    lines += [
        "## Clustered signatures",
        "",
        "| Error / symptom pattern | Root cause | Recovery action | Success (k/n) | Seen in |",
        "|---|---|---|---|---|",
    ]
    for c in sorted(clusters, key=lambda d: -d["n"]):
        seen = ", ".join(c["classes"]) or "—"
        lines.append(
            f"| {c['pattern']} | {c['root_cause']} | {c['action']} | {c['k']}/{c['n']} | {seen} |"
        )

    if unclustered:
        lines += [
            "",
            "## Unclustered incidents",
            "",
            "_Not yet generalized into a signature — review individually._",
            "",
        ]
        for u in unclustered:
            lines.append(
                f"- **{u['run']}** [Stage {u['stage']}] {u['diagnosis']} → "
                f"{u['fix']} ({u['outcome']})"
            )

    return "\n".join(lines) + "\n"
