#!/usr/bin/env python3
"""Enumerate alternative repeat-unit cuts of the SAME polymer.

Why this exists. EMC types the repeat GROUP before it resolves the `*` connection points, so
an atom adjacent to a `*` cannot complete an environment pattern that names all its
neighbours and falls back to a generic type. In OPLS-AA that shows up as a carbon typed `c4`
where the field's own convention wants `c4oe`, and `c4` carries none of `c4oe`'s increments --
so the build dies on a parameter that exists, for a type that should never have been assigned.
Moving the cut so the boundary atoms are ones where the generic type is CORRECT sidesteps it
without touching a field file or inventing a number.

The invariant this module enforces, and the reason it is not just string surgery: a re-cut
must PRESERVE THE POLYMER. Cutting `*CCO*` (PEO, backbone C-C-O) to `*CCOCC*` yields a repeat
with backbone C-C-O-C-C -- four carbons per ether oxygen instead of two, which is
poly(tetramethylene oxide), a different material that happens to build. Every candidate here
is generated by cutting the DIMER at two bonds exactly one period apart, so the repeat length
and composition are preserved by construction, and `verify_same_polymer` re-checks it.
"""

from __future__ import annotations

from rdkit import Chem
from rdkit import RDLogger

RDLogger.DisableLog("rdApp.*")


def _dummies(mol) -> list:
    return [a.GetIdx() for a in mol.GetAtoms() if a.GetAtomicNum() == 0]


def repeat_signature(smiles: str):
    """(sorted heavy-atom element counts, backbone element sequence) for the repeat unit.

    The identity a re-cut must not change. The backbone sequence is compared as a cyclic
    rotation, because that is exactly what a different cut of the same chain produces.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    ds = _dummies(mol)
    if len(ds) != 2:
        return None
    counts = {}
    for a in mol.GetAtoms():
        if a.GetAtomicNum() != 0:
            counts[a.GetSymbol()] = counts.get(a.GetSymbol(), 0) + 1
            counts["H"] = counts.get("H", 0) + a.GetTotalNumHs()
    path = Chem.GetShortestPath(mol, ds[0], ds[1])
    backbone = tuple(mol.GetAtomWithIdx(i).GetSymbol() for i in path[1:-1])
    return tuple(sorted(counts.items())), backbone


def _rotations(seq):
    return {seq[i:] + seq[:i] for i in range(len(seq))}


def verify_same_polymer(original: str, candidate: str) -> bool:
    a, b = repeat_signature(original), repeat_signature(candidate)
    if a is None or b is None:
        return False
    if a[0] != b[0]:
        return False                      # composition changed -- different monomer
    return b[1] in _rotations(a[1])       # backbone is a rotation of the same period


def _build_dimer(mol):
    """Head-to-tail dimer keeping the outer two dummies. Returns (dimer, left_d, right_d)."""
    ds = _dummies(mol)
    if len(ds) != 2:
        return None
    combo = Chem.RWMol(Chem.CombineMols(mol, mol))
    n = mol.GetNumAtoms()
    a_tail, b_head = ds[1], ds[0] + n              # A's right dummy, B's left dummy
    a_anchor = combo.GetAtomWithIdx(a_tail).GetNeighbors()[0].GetIdx()
    b_anchor = combo.GetAtomWithIdx(b_head).GetNeighbors()[0].GetIdx()
    combo.AddBond(a_anchor, b_anchor, Chem.BondType.SINGLE)
    for idx in sorted([a_tail, b_head], reverse=True):
        combo.RemoveAtom(idx)
    dimer = combo.GetMol()
    try:
        Chem.SanitizeMol(dimer)
    except Exception:
        return None
    ds2 = _dummies(dimer)
    return (dimer, ds2[0], ds2[1]) if len(ds2) == 2 else None


def recut_candidates(smiles: str, allow_stereo: bool = False) -> list:
    """Alternative repeat-unit SMILES for the same polymer, best boundary first.

    Skips stereochemistry by default. EMC reads tacticity from the SMILES' own @/@@ and the
    parity a repeat unit expresses INVERTS when a `*` sits inside the stereocentre's branch,
    so a re-cut that moves the `*` can silently flip an isotactic build to syndiotactic.
    That is a correctness question of its own, not something to fold into a coverage sweep.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return []
    if not allow_stereo and (any(a.GetChiralTag() != Chem.ChiralType.CHI_UNSPECIFIED
                                 for a in mol.GetAtoms())
                             or any(b.GetStereo() != Chem.BondStereo.STEREONONE
                                    for b in mol.GetBonds())):
        return []

    built = _build_dimer(mol)
    if built is None:
        return []
    dimer, dl, dr = built
    path = Chem.GetShortestPath(dimer, dl, dr)
    chain = list(path[1:-1])
    if len(chain) < 2 or len(chain) % 2:
        return []
    L = len(chain) // 2                     # backbone atoms per repeat

    out = []
    for k in range(1, L):                   # k=0 reproduces the original cut
        b1 = dimer.GetBondBetweenAtoms(chain[k - 1], chain[k])
        b2 = dimer.GetBondBetweenAtoms(chain[k - 1 + L], chain[k + L])
        if b1 is None or b2 is None:
            continue
        # Only single, acyclic bonds: cutting a ring bond opens the ring and cutting a
        # double bond changes the backbone's bonding, both of which change the polymer.
        if any(b.GetBondType() != Chem.BondType.SINGLE or b.IsInRing() for b in (b1, b2)):
            continue
        try:
            frags = Chem.FragmentOnBonds(dimer, [b1.GetIdx(), b2.GetIdx()],
                                         dummyLabels=[(0, 0), (0, 0)])
            pieces = Chem.GetMolFrags(frags, asMols=True, sanitizeFrags=True)
        except Exception:
            continue
        for piece in pieces:
            if len(_dummies(piece)) != 2:
                continue
            cand = Chem.MolToSmiles(piece)
            if verify_same_polymer(smiles, cand) and cand != smiles:
                out.append((_boundary_score(cand), cand))
                break

    seen, ranked = set(), []
    for score, cand in sorted(out, key=lambda x: -x[0]):
        if cand not in seen:
            seen.add(cand)
            ranked.append(cand)
    return ranked


def _boundary_score(smiles: str) -> int:
    """How safe this cut's boundary atoms are: +1 per `*`-adjacent carbon that has no
    heteroatom neighbour, so the generic type EMC assigns it is the right one anyway."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return -1
    score = 0
    for d in _dummies(mol):
        for nb in mol.GetAtomWithIdx(d).GetNeighbors():
            if nb.GetAtomicNum() != 6:
                continue
            if all(x.GetAtomicNum() in (0, 1, 6)
                   for x in nb.GetNeighbors()):
                score += 1
    return score


if __name__ == "__main__":
    import sys
    for s in sys.argv[1:]:
        print(s, "->", recut_candidates(s))
